
title: Kea Johnston, Egyptologist #Your awesome title
email: sydneycarton@gmail.com
description: > # this means to ignore newlines until "baseurl"
  A blog for Kea Johnston, Egyptologist

baseurl: # the subpath of the site
url: https://nanythemummy.github.io/ # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

user:
  name: Kea Johnston
  pic: /assets/img/hatmehit.jpeg
  job: Egyptologist
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github
  - vendor/*

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

excerpt_separator: <!--more-->

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false